services:
  education_database:
    container_name: "library_database"
    image: postgres:17.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=education_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - container


volumes:
  postgres_data:
networks:
  container:
    driver: bridge
