services:
  library_database:
    container_name: "library_database"
    image: postgres:17.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - container


volumes:
  postgres_data:
networks:
  container:
    driver: bridge
