"""added_email_password_to_author

Revision ID: 5046f32ee386
Revises: 384fa55467a6
Create Date: 2025-09-05 00:06:43.695300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5046f32ee386'
down_revision: Union[str, Sequence[str], None] = '384fa55467a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('authors', sa.Column('password', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_authors_email'), 'authors', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authors_email'), table_name='authors')
    op.drop_column('authors', 'password')
    op.drop_column('authors', 'email')
    # ### end Alembic commands ###
